### PR TITLE
Fix bitcoin cash validation bugs

### LINKED ISSUE #97: Bitcoin Cash Stops to Sync
Bitcoin cash stops to sync after block #547592. It keeps throwing error "Not Equal Bits"

### PR DESCRIPTION
**Pull request by omurovch**
Close #97

### CODE REVIEW

File: bitcoinkit/src/main/kotlin/io/horizontalsystems/bitcoinkit/network/Peer.kt [hunk 1]
```diff
@@ -164,7 +167,8 @@ class Peer(val host: String, private val network: NetworkParameters, private val
 
     private fun handleMerkleBlockMessage(message: MerkleBlockMessage) {
         for (task in tasks) {
-            if (task.handleMerkleBlock(message.merkleBlock)) {
+            val merkleBlock = merkleBlockExtractor.extract(message)
+            if (task.handleMerkleBlock(merkleBlock)) {
```
Comment (abdrasulov) [inline bitcoinkit/src/main/kotlin/io/horizontalsystems/bitcoinkit/network/Peer.kt]: let's inline val merkleBlock
